prefixes = (
    ("bon", "good"),
    ("bo", "in-law"),
    ("de", "de"),
    ("dis", "separation"),
    ("eks", "ex (former)"),
    ("ek", "commencement"),
    ("ge", "both sexes"),
    ("mal", "opposite of"),
    ("mis", "incorrectly"),
    ("pra", "primordiality"),
    ("re", "again, re"),
    ("al", "toward"),
    ("anstataŭ", "instead of"),
    ("antaŭ", "before"),
    ("apud", "beside"),
    ("ĉe", "at"),
    ("ĉirkaŭ", "about"),
    ("de", "of"),
    ("dum", "during/while"),
    ("ekde", "since"),
    ("el", "from"),
    ("en", "into"),
    ("eksteren", "outward"),
    ("ekster", "outside"),
    ("for", "away"),
    ("ĝis", "until"),
    ("inter", "among"),
    ("kontraŭ", "contra"),
    ("krom", "except"),
    ("kun", "with"),
    ("laŭ", "according to"),
    ("malgraŭ", "despite"),
    ("ne", "no"),
    ("ol", "than"),
    ("per", "through use of"),
    ("plus", "greater than"),
    ("post", "after"),
    ("por", "on behalf of"),
    ("po", "at the rate of"),
    ("preter", "beyond"),
    ("pri", "concerning"),
    ("pro", "because of"),
    ("sen", "without"),
    ("sub", "below"),
    ("sur", "upon"),
    ("super", "over"),
    ("trans", "across"),
    ("tra", "through"),
)

suffixes = (
    ("aĉ", "low quality"),
    ("ad", "prolonged/repetitive"),
    ("aĵ", "product"),
    ("an", "membership of"),
    ("ar", "collective"),
    ("cĵ", "masculine pet name"),
    ("ebl", "able"),
    ("ec", "quality"),
    ("eg", "larger sized"),
    ("ej", "place of"),
    ("em", "disposition"),
    ("end", "obligation"),
    ("er", "small element of"),
    ("estr", "chief"),
    ("et", "smaller sized"),
    ("id", "descendent"),
    ("ig", "cause to do/be"),
    ("iĝ", "to become"),
    ("il", "tool"),
    ("in", "feminine"),
    ("ind", "worthy of"),
    ("ing", "holder"),
    ("ism", "ism"),
    ("ist", "professional"),
    ("nj", "feminine pet name"),
    ("obl", "multiple of"),
    ("on", "fraction of"),
    ("op", "groups of"),
    ("uj", "container"),
    ("ul", "person"),
    ("um", "<no fixed meaning>")
)



final_parts = (
    ("n", "accusative"),
    ("j", "plural"),
    ("a", "adj/quality"),
    ("al", "reason"),
    ("am", "time"),
    ("e", "adv/place"),
    ("el", "manner"),
    ("es", "ownership"),
    ("i", "verb"),
    ("o", "noun/thing"),
    ("om", "amount"),
    ("u", "individual"),
    ("us", "conditional")
)